<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * English strings.
 *
 * @package    tool_moodledoctor
 * @copyright  2026 Eduardo Kraus
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die;

$string['additionalcontext'] = 'Additional context';
$string['additionalcontext_help'] = 'Optional operational context. Do not intentionally paste secrets; the sanitizer is a defence-in-depth control, not an excuse to share credentials.';
$string['aifailed'] = 'AI diagnosis failed: {$a}';
$string['aiheading'] = 'AI interpretation';
$string['ainotfact'] = 'The section below contains hypotheses and recommendations generated by AI. Treat it as interpretation, not as collected fact.';
$string['cancelpreview'] = 'Cancel';
$string['checklistquestion'] = 'Investigation goal';
$string['checklistquestion_help'] = 'Optional. Example: “Intermittent 504 responses after course restore”.';
$string['checkliststatus'] = 'Checklist context';
$string['confirmsend'] = 'Send this payload to AI';
$string['cronstatus'] = 'Cron and task status';
$string['dangerousactionsdisabled'] = 'Moodle Doctor is read-only. It does not execute shell commands, SQL generated by AI, configuration changes, cache purges, plugin upgrades, task runs, or other automatic fixes.';
$string['environmentstatus'] = 'Environment status';
$string['errorinput'] = 'Error message or stack trace';
$string['errorinput_help'] = 'Paste the error or stack trace. Moodle Doctor sanitizes secrets before creating the AI preview.';
$string['factsexplanation'] = 'These facts are collected deterministically by Moodle Doctor. They are shown separately from any AI interpretation.';
$string['factsheading'] = 'Collected facts';
$string['generatechecklist'] = 'Prepare checklist preview';
$string['healthsummary'] = 'System health summary';
$string['invalidpreview'] = 'The preview is missing, expired, already used, or belongs to another session.';
$string['manualtoolarge'] = 'The supplied text is too large. Limit each field to {$a} characters.';
$string['moodledoctor:use'] = 'Use Moodle Doctor';
$string['noinstalledplugins'] = 'No installed plugins were found.';
$string['nopermission'] = 'You do not have permission to use Moodle Doctor.';
$string['plugincomponent'] = 'Plugin';
$string['plugincontext'] = 'Observed problem';
$string['plugincontext_help'] = 'Optional symptoms or error text related to the selected plugin.';
$string['pluginname'] = 'Moodle Doctor';
$string['pluginstatus'] = 'Plugin status';
$string['prepareai'] = 'Prepare AI diagnosis';
$string['previewexplanation'] = 'This is the exact message payload Moodle Doctor will pass to local_ai_bridge. The bridge may additionally apply the system instruction configured for the moodledoctor-diagnose purpose.';
$string['previewheading'] = 'AI payload preview';
$string['previewmanual'] = 'Sanitize and preview';
$string['privacy:metadata:external'] = 'When an administrator explicitly confirms an AI diagnosis, sanitized diagnostic data is routed through local_ai_bridge to the AI provider configured by the site.';
$string['privacy:metadata:external:diagnosticfacts'] = 'Deterministic Moodle diagnostic facts selected for the requested diagnosis.';
$string['privacy:metadata:external:manualcontext'] = 'Sanitized error text, stack traces, or investigation context manually supplied by the administrator.';
$string['sanitizednotice'] = 'All AI-bound content passes through the sanitizer. Known credentials, tokens, cookies, session identifiers, Authorization headers, DSNs and URL credentials are redacted.';
$string['tab:checklist'] = 'Investigation checklist';
$string['tab:cron'] = 'Diagnose cron';
$string['tab:environment'] = 'Diagnose environment';
$string['tab:error'] = 'Explain error';
$string['tab:health'] = 'Health check';
$string['tab:plugin'] = 'Diagnose plugin';
$string['unknownplugin'] = 'Unknown plugin component.';
